# Copyright (c) 2020 Ryan Cross
# SPDX-License-Identifier: MIT

# Habilitar Display OLED
CONFIG_ZMK_DISPLAY=y

# Habilitar Encoders
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

# Habilitar RGB Underglow
CONFIG_ZMK_RGB_UNDERGLOW=y
CONFIG_WS2812_STRIP=y

# Habilitar ZMK Studio (Mapeamento de teclas em tempo real pelo App gráfico)
CONFIG_ZMK_STUDIO=y
# Desativa o bloqueio automático de segurança do ZMK Studio
# Assim você não precisa de uma tecla específica de "unlock" no teclado para conectar
CONFIG_ZMK_STUDIO_LOCKING=n

# Habilitar sono profundo para economizar bateria
CONFIG_ZMK_SLEEP=y
